### ISSUE TITLE
Use camel-spring-boot for automatic camel configuration

### ISSUE THREAD

**Issue by mkhl** [ewerk/sample_spring-boot-camel-mongo-jdk8#13]
Camel 2.15 will include a spring-boot component that will autoconfigure Camel and integrate it with the Spring context. We should use that feature once Camel 2.15 is out.

See also: http://henryk-konsek.blogspot.de/2014/10/using-apache-camel-with-spring-boot.html

**Comment by holgerstolzenberg** [comment]
Rejected.
